# include <iostream>
using namespace std;

int main() {
        cout << "nwbda";
        cout << "uqhxm";
        cout << "vayyr";
        cout << "oqcjy";
        cout << "kyrip";
        cout << "rxohf";
        cout << "eggvt";
        cout << "rjnyl";
        cout << "rjbwp";
        cout << "ocwrf";
        cout << "tptjl";
        cout << "gruog";
        cout << "ipaof";
        cout << "aymqh";
        cout << "ifdsq";
        cout << "kfmcj";
        cout << "vylns";
        cout << "rfkww";
        cout << "nlhma";
        cout << "cqfxm";
        cout << "eebjs";
        cout << "dbgfg";
        cout << "felvr";
        cout << "mntsr";
        cout << "elbcg";
        cout << "evyyk";
        cout << "jxomc";
        cout << "hnrsq";
        cout << "uwplm";
        cout << "mermm";
        cout << "lwdcd";
        cout << "tyctw";
        cout << "jvdib";
        cout << "chlww";
        cout << "hdufa";
        cout << "ovcyp";
        cout << "vpaql";
        cout << "psfcn";
        cout << "ankox";
        cout << "efvxv";
        cout << "jvmaq";
        cout << "ououn";
        cout << "aoxwb";
return 0;
}
